### ISSUE TITLE
Executing ST_X and ST_Y together with ST_Centroid yield the same number, but when executed separately yield different latitude, longitude coordinates

### ISSUE THREAD

**Issue by jaanli** [duckdblabs/duckdb_spatial#103] opened 2023-07-24 22:27 UTC
This is a shape file for United States' census block groups we need to teach courses:  https://www2.census.gov/geo/tiger/GENZ2020/shp/cb_2020_us_bg_500k.zip 

(from https://www.census.gov/geographies/mapping-files/time-series/geo/cartographic-boundary.2020.html)

Full example: https://github.com/onefact/data_build_tool_for_datathinking.org/blob/main/notebooks/united-states-census-block-groups.ipynb

Loading this and trying to convert the centroids of the shapes yields the same number for the latitude and longitude, and the command thus needs to be split up.

Running the commands separately yields the first GEOID (340010104011) first two digits correspond to a place in New Jersey (https://www.census.gov/library/reference/code-lists/ansi/ansi-codes-for-states.html). 

<img width="938" alt="image" src="https://github.com/duckdblabs/duckdb_spatial/assets/5317244/d2878a8f-be63-49f3-b91d-7ad90af99fe5">

cc @Maxxen -- thank you for your help on this!!

**Comment by Maxxen** [comment] 2023-07-25 08:29
I cannot reproduce this through the DuckDB CLI.
```sql
LOAD spatial;
CREATE TABLE t1 AS SELECT * FROM st_read('/vsizip/./tmp/data/cb_2020_us_bg_500k.zip');
SELECT GEOID, st_x(st_centroid(st_geomfromwkb(wkb_geometry))) as longitude, st_y(st_centroid(st_geomfromwkb(wkb_geometry))) as latitude FROM t1;
```
```sql
┌──────────────┬─────────────────────┬────────────────────┐
│    GEOID     │      longitude      │      latitude      │
│   varchar    │       double        │       double       │
├──────────────┼─────────────────────┼────────────────────┤
│ 340010104011 │  -74.61784746192461 │  39.52663347545994 │
│ 340010104032 │  -74.55831008755985 │  39.46473816843732 │
│ 450830218032 │  -81.99932374394618 │ 35.012646979869146 │
│ 450830220043 │  -81.85324991388869 │  34.90714457742036 │
│ 450830217002 │   -81.9681853248782 │  34.95995370746854 │
│ 450830231013 │    -82.117984510999 │  34.91669624079691 │
│ 551332024003 │   -88.2226547700119 │   42.9962661636953 │
│ 551332020012 │  -88.28675538753306 │  42.90682126823693 │
│ 551332008033 │  -88.13100429439484 │ 43.096977412800605 │
│ 551170004001 │  -87.74672955564294 │   43.7601503691619 │
│ 510594901013 │   -77.4465464711213 │  38.85885475170101 │
...
```

I wonder if this is related to #88, but that was through the R-client.

**Comment by Maxxen** [comment] 2023-07-25 08:34
Aha! But I can reproduce It through python
```python
import duckdb
duckdb.sql
duckdb.sql('LOAD spatial')
duckdb.sql('SELECT 42').show()
duckdb.sql("CREATE TABLE t1 AS SELECT * FROM st_read('/vsizip/./tmp/data/cb_2020_us_bg_500k.zip');")
duckdb.sql('SELECT GEOID, st_x(st_centroid(st_geomfromwkb(wkb_geometry))) as longitude, st_y(st_centroid(st_geomfromwkb(wkb_geometry))) as latitude FROM t1;').show()
```
Il look into it.

**Comment by Maxxen** [comment] 2023-07-25 12:12
So it seems like DuckDB's optimiser is too aggressive and thinks that the scalar functions st_x and st_y are equivalent, and therefore replaces the result of one with the other as part of the common subexpression elimination optimization pass. 

For some reason this only occurs when spatial is dynamically loaded into DuckDB at runtime (as is the case when running from clients), which is why we haven't been able to catch it through our tests yet (were we statically compile spatial into duckdb).

I think this is related to another long-standing issue regarding duckdb extensions losing type information, (e.g. the same reason extension exceptions don't get caught) which would explain why e.g. in this case the function pointers fail to cast, turn into nullptr and thus considered equivalent.

**Comment by jaanli** [comment] 2023-07-25 12:58
Super helpful, thank you so much @Maxxen !! I was imagining it is because of some type of caching or re-use of functions -- that makes sense :) 🙏 🙏 🙏

**Comment by jaakla** [comment] 2023-08-01 16:19
Simple reproduction:
```
with geom as (select st_geomfromtext('POINT (106.8138063 10.8594813)') g) select st_x(geom.g),st_y(geom.g) from geom;
┌──────────────┬──────────────┐
│ st_x(geom.g) │ st_y(geom.g) │
│    double    │    double    │
├──────────────┼──────────────┤
│  106.8138063 │  106.8138063 │
└──────────────┴──────────────┘
```

**Comment by jaanli** [comment] 2023-08-02 21:49
You're amazing @Maxxen thank you!!! @stockdaleb108 and I will try this out 🙏 🙏 🙏

**Comment by Maxxen** [comment] 2023-08-13 17:46
Closing this as it is fixed on the latest nightly builds.

**Closed by Maxxen** 2023-08-13 17:46 UTC
